CREATE TABLE IF NOT EXISTS muser(
  uid INTEGER PRIMARY KEY AUTOINCREMENT,
  passwd VARCHAR(32) NOT NULL,
  uname VARCHAR(32) NOT NULL,
  status INTEGER DEFAULT 0,
  time TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS mmessage(
  uid INTEGER NOT NULL,
  type INTEGER NOT NULL,
  tid INTEGER DEFAULT NULL,
  msg TEXT NOT NULL,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mfile (
  uid INTEGER NOT NULL,
  tid INTEGER NOT NULL,
  filename TEXT NOT NULL,
  size INTEGER NOT NULL,
  time TIMESTAMP DEFAULT NULL,
  status INTEGER DEFAULT 0,
  curr INTEGER DEFAULT 0
);

-- 每次新建表时重置登陆状态
UPDATE
  muser
SET
  status = 0,
  time = NULL;